package com.pzx.downloader.utils

import android.app.Activity
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.text.TextUtils
import android.util.Log
import androidx.core.content.FileProvider
import java.io.File
import java.util.*

/**
 * File Name : FileOpenUtils
 * Created by : PanZX on 2020/03/05
 * Email : 644173944@qq.com
 * Github : https://github.com/Pulini
 * Remark： 打开文件
 */
object FileOpenUtils {
    /**
     * 使用自定义方法打开文件
     */
    fun openFile(act: Activity, file: File) {
        val intent = Intent()
        val authority = "com.pzx.downloader.fileprovider"
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            //  此处注意替换包名，
            val contentUri = FileProvider.getUriForFile(act, authority, file)
            intent.setDataAndType(contentUri,
                getFileMIME(file)
            )
        } else {
            //也可使用 Uri.parse("file://"+file.getAbsolutePath());
            intent.setDataAndType(Uri.fromFile(file),
                getFileMIME(file)
            )
        }

        //以下设置都不是必须的
        intent.action = Intent.ACTION_VIEW // 系统根据不同的Data类型，通过已注册的对应Application显示匹配的结果。
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK) //系统会检查当前所有已创建的Task中是否有该要启动的Activity的Task
        //若有，则在该Task上创建Activity；若没有则新建具有该Activity属性的Task，并在该新建的Task上创建Activity。
        intent.addCategory(Intent.CATEGORY_DEFAULT) //按照普通Activity的执行方式执行
        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        act.startActivity(intent)
    }

    /**
     * 使用自定义方法获得文件的MIME类型
     */
    private fun getFileMIME(file: File): String? {
        var type = "*/*"
        val fName = file.name
        //获取后缀名前的分隔符"."在fName中的位置。
        val dotIndex = fName.lastIndexOf(".")
        if (dotIndex > 0) {
            //获取文件的后缀名
            val end = fName.substring(dotIndex, fName.length).toLowerCase(Locale.getDefault())
            //在MIME和文件类型的匹配表中找到对应的MIME类型。
            val map = FileMIME.mIMEMap
            if (!TextUtils.isEmpty(end) && map.containsKey(end)) {
                type = map[end].toString()
            }
        }
        Log.i("bqt", "我定义的MIME类型为：$type")
        return type
    }

    internal object FileMIME {
        private val mapSimple =
            HashMap<String, String>()
        private val mapAll =
            HashMap<String, String>()

        /**
         * 常用"文件扩展名—MIME类型"匹配表。
         * 注意，此表并不全，也并不是唯一的，就像有人喜欢用浏览器打开TXT一样，你可以根据自己的爱好自定义。
         */
        val mIMEMap: HashMap<String, String>
            get() {
                if (mapSimple.size == 0) {
                    mapSimple[".3gp"] = "video/3gpp"
                    mapSimple[".apk"] = "application/vnd.android.package-archive"
                    mapSimple[".asf"] = "video/x-ms-asf"
                    mapSimple[".avi"] = "video/x-msvideo"
                    mapSimple[".bin"] = "application/octet-stream"
                    mapSimple[".bmp"] = "image/bmp"
                    mapSimple[".c"] = "text/plain"
                    mapSimple[".chm"] = "application/x-chm"
                    mapSimple[".class"] = "application/octet-stream"
                    mapSimple[".conf"] = "text/plain"
                    mapSimple[".cpp"] = "text/plain"
                    mapSimple[".doc"] = "application/msword"
                    mapSimple[".docx"] = "application/msword"
                    mapSimple[".exe"] = "application/octet-stream"
                    mapSimple[".gif"] = "image/gif"
                    mapSimple[".gtar"] = "application/x-gtar"
                    mapSimple[".gz"] = "application/x-gzip"
                    mapSimple[".h"] = "text/plain"
                    mapSimple[".htm"] = "text/html"
                    mapSimple[".html"] = "text/html"
                    mapSimple[".jar"] = "application/java-archive"
                    mapSimple[".java"] = "text/plain"
                    mapSimple[".jpeg"] = "image/jpeg"
                    mapSimple[".jpg"] = "image/jpeg"
                    mapSimple[".js"] = "application/x-javascript"
                    mapSimple[".log"] = "text/plain"
                    mapSimple[".m3u"] = "audio/x-mpegurl"
                    mapSimple[".m4a"] = "audio/mp4a-latm"
                    mapSimple[".m4b"] = "audio/mp4a-latm"
                    mapSimple[".m4p"] = "audio/mp4a-latm"
                    mapSimple[".m4u"] = "video/vnd.mpegurl"
                    mapSimple[".m4v"] = "video/x-m4v"
                    mapSimple[".mov"] = "video/quicktime"
                    mapSimple[".mp2"] = "audio/x-mpeg"
                    mapSimple[".mp3"] = "audio/x-mpeg"
                    mapSimple[".mp4"] = "video/mp4"
                    mapSimple[".mpc"] = "application/vnd.mpohun.certificate"
                    mapSimple[".mpe"] = "video/mpeg"
                    mapSimple[".mpeg"] = "video/mpeg"
                    mapSimple[".mpg"] = "video/mpeg"
                    mapSimple[".mpg4"] = "video/mp4"
                    mapSimple[".mpga"] = "audio/mpeg"
                    mapSimple[".msg"] = "application/vnd.ms-outlook"
                    mapSimple[".ogg"] = "audio/ogg"
                    mapSimple[".pdf"] = "application/pdf"
                    mapSimple[".png"] = "image/png"
                    mapSimple[".pps"] = "application/vnd.ms-powerpoint"
                    mapSimple[".ppt"] = "application/vnd.ms-powerpoint"
                    mapSimple[".pptx"] = "application/vnd.ms-powerpoint"
                    mapSimple[".prop"] = "text/plain"
                    mapSimple[".rar"] = "application/x-rar-compressed"
                    mapSimple[".rc"] = "text/plain"
                    mapSimple[".rmvb"] = "audio/x-pn-realaudio"
                    mapSimple[".rtf"] = "application/rtf"
                    mapSimple[".sh"] = "text/plain"
                    mapSimple[".tar"] = "application/x-tar"
                    mapSimple[".tgz"] = "application/x-compressed"
                    mapSimple[".txt"] = "text/plain"
                    mapSimple[".wav"] = "audio/x-wav"
                    mapSimple[".wma"] = "audio/x-ms-wma"
                    mapSimple[".wmv"] = "audio/x-ms-wmv"
                    mapSimple[".wps"] = "application/vnd.ms-works"
                    mapSimple[".xml"] = "text/plain"
                    mapSimple[".xls"] = "application/vnd.ms-excel"
                    mapSimple[".xlsx"] = "application/vnd.ms-excel"
                    mapSimple[".z"] = "application/x-compress"
                    mapSimple[".zip"] = "application/zip"
                    mapSimple[""] = "*/*"
                }
                return mapSimple
            }

        /**
         * 常用"文件扩展名—MIME类型"匹配表。
         * 注意，此表并不全，也并不是唯一的，就像有人喜欢用浏览器打开TXT一样，你可以根据自己的爱好自定义。
         */
        val allMIMEMap: HashMap<String, String>
            get() {
                if (mapAll.size == 0) {
                    mapAll["3gp"] = "video/3gpp"
                    mapAll["aab"] = "application/x-authoware-bin"
                    mapAll["aam"] = "application/x-authoware-map"
                    mapAll["aas"] = "application/x-authoware-seg"
                    mapAll["ai"] = "application/postscript"
                    mapAll["aif"] = "audio/x-aiff"
                    mapAll["aifc"] = "audio/x-aiff"
                    mapAll["aiff"] = "audio/x-aiff"
                    mapAll["als"] = "audio/X-Alpha5"
                    mapAll["amc"] = "application/x-mpeg"
                    mapAll["ani"] = "application/octet-stream"
                    mapAll["apk"] = "application/vnd.android.package-archive"
                    mapAll["asc"] = "text/plain"
                    mapAll["asd"] = "application/astound"
                    mapAll["asf"] = "video/x-ms-asf"
                    mapAll["asn"] = "application/astound"
                    mapAll["asp"] = "application/x-asap"
                    mapAll["asx"] = "video/x-ms-asf"
                    mapAll["au"] = "audio/basic"
                    mapAll["avb"] = "application/octet-stream"
                    mapAll["avi"] = "video/x-msvideo"
                    mapAll["awb"] = "audio/amr-wb"
                    mapAll["bcpio"] = "application/x-bcpio"
                    mapAll["bin"] = "application/octet-stream"
                    mapAll["bld"] = "application/bld"
                    mapAll["bld2"] = "application/bld2"
                    mapAll["bmp"] = "image/bmp"
                    mapAll["bpk"] = "application/octet-stream"
                    mapAll["bz2"] = "application/x-bzip2"
                    mapAll["cal"] = "image/x-cals"
                    mapAll["ccn"] = "application/x-cnc"
                    mapAll["cco"] = "application/x-cocoa"
                    mapAll["cdf"] = "application/x-netcdf"
                    mapAll["cgi"] = "magnus-internal/cgi"
                    mapAll["chat"] = "application/x-chat"
                    mapAll["class"] = "application/octet-stream"
                    mapAll["clp"] = "application/x-msclip"
                    mapAll["cmx"] = "application/x-cmx"
                    mapAll["co"] = "application/x-cult3d-object"
                    mapAll["cod"] = "image/cis-cod"
                    mapAll["cpio"] = "application/x-cpio"
                    mapAll["cpt"] = "application/mac-compactpro"
                    mapAll["crd"] = "application/x-mscardfile"
                    mapAll["csh"] = "application/x-csh"
                    mapAll["csm"] = "chemical/x-csml"
                    mapAll["csml"] = "chemical/x-csml"
                    mapAll["css"] = "text/css"
                    mapAll["cur"] = "application/octet-stream"
                    mapAll["dcm"] = "x-lml/x-evm"
                    mapAll["dcr"] = "application/x-director"
                    mapAll["dcx"] = "image/x-dcx"
                    mapAll["dhtml"] = "text/html"
                    mapAll["dir"] = "application/x-director"
                    mapAll["dll"] = "application/octet-stream"
                    mapAll["dmg"] = "application/octet-stream"
                    mapAll["dms"] = "application/octet-stream"
                    mapAll["doc"] = "application/msword"
                    mapAll["dot"] = "application/x-dot"
                    mapAll["dvi"] = "application/x-dvi"
                    mapAll["dwf"] = "drawing/x-dwf"
                    mapAll["dwg"] = "application/x-autocad"
                    mapAll["dxf"] = "application/x-autocad"
                    mapAll["dxr"] = "application/x-director"
                    mapAll["ebk"] = "application/x-expandedbook"
                    mapAll["emb"] = "chemical/x-embl-dl-nucleotide"
                    mapAll["embl"] = "chemical/x-embl-dl-nucleotide"
                    mapAll["eps"] = "application/postscript"
                    mapAll["eri"] = "image/x-eri"
                    mapAll["es"] = "audio/echospeech"
                    mapAll["esl"] = "audio/echospeech"
                    mapAll["etc"] = "application/x-earthtime"
                    mapAll["etx"] = "text/x-setext"
                    mapAll["evm"] = "x-lml/x-evm"
                    mapAll["evy"] = "application/x-envoy"
                    mapAll["exe"] = "application/octet-stream"
                    mapAll["fh4"] = "image/x-freehand"
                    mapAll["fh5"] = "image/x-freehand"
                    mapAll["fhc"] = "image/x-freehand"
                    mapAll["fif"] = "image/fif"
                    mapAll["fm"] = "application/x-maker"
                    mapAll["fpx"] = "image/x-fpx"
                    mapAll["fvi"] = "video/isivideo"
                    mapAll["gau"] = "chemical/x-gaussian-input"
                    mapAll["gca"] = "application/x-gca-compressed"
                    mapAll["gdb"] = "x-lml/x-gdb"
                    mapAll["gif"] = "image/gif"
                    mapAll["gps"] = "application/x-gps"
                    mapAll["gtar"] = "application/x-gtar"
                    mapAll["gz"] = "application/x-gzip"
                    mapAll["hdf"] = "application/x-hdf"
                    mapAll["hdm"] = "text/x-hdml"
                    mapAll["hdml"] = "text/x-hdml"
                    mapAll["hlp"] = "application/winhlp"
                    mapAll["hqx"] = "application/mac-binhex40"
                    mapAll["htm"] = "text/html"
                    mapAll["html"] = "text/html"
                    mapAll["hts"] = "text/html"
                    mapAll["ice"] = "x-conference/x-cooltalk"
                    mapAll["ico"] = "application/octet-stream"
                    mapAll["ief"] = "image/ief"
                    mapAll["ifm"] = "image/gif"
                    mapAll["ifs"] = "image/ifs"
                    mapAll["imy"] = "audio/melody"
                    mapAll["ins"] = "application/x-NET-Install"
                    mapAll["ips"] = "application/x-ipscript"
                    mapAll["ipx"] = "application/x-ipix"
                    mapAll["it"] = "audio/x-mod"
                    mapAll["itz"] = "audio/x-mod"
                    mapAll["ivr"] = "i-world/i-vrml"
                    mapAll["j2k"] = "image/j2k"
                    mapAll["jad"] = "text/vnd.sun.j2me.app-descriptor"
                    mapAll["jam"] = "application/x-jam"
                    mapAll["jar"] = "application/java-archive"
                    mapAll["jnlp"] = "application/x-java-jnlp-file"
                    mapAll["jpe"] = "image/jpeg"
                    mapAll["jpeg"] = "image/jpeg"
                    mapAll["jpg"] = "image/jpeg"
                    mapAll["jpz"] = "image/jpeg"
                    mapAll["js"] = "application/x-javascript"
                    mapAll["jwc"] = "application/jwc"
                    mapAll["kjx"] = "application/x-kjx"
                    mapAll["lak"] = "x-lml/x-lak"
                    mapAll["latex"] = "application/x-latex"
                    mapAll["lcc"] = "application/fastman"
                    mapAll["lcl"] = "application/x-digitalloca"
                    mapAll["lcr"] = "application/x-digitalloca"
                    mapAll["lgh"] = "application/lgh"
                    mapAll["lha"] = "application/octet-stream"
                    mapAll["lml"] = "x-lml/x-lml"
                    mapAll["lmlpack"] = "x-lml/x-lmlpack"
                    mapAll["lsf"] = "video/x-ms-asf"
                    mapAll["lsx"] = "video/x-ms-asf"
                    mapAll["lzh"] = "application/x-lzh"
                    mapAll["m13"] = "application/x-msmediaview"
                    mapAll["m14"] = "application/x-msmediaview"
                    mapAll["m15"] = "audio/x-mod"
                    mapAll["m3u"] = "audio/x-mpegurl"
                    mapAll["m3url"] = "audio/x-mpegurl"
                    mapAll["ma1"] = "audio/ma1"
                    mapAll["ma2"] = "audio/ma2"
                    mapAll["ma3"] = "audio/ma3"
                    mapAll["ma5"] = "audio/ma5"
                    mapAll["man"] = "application/x-troff-man"
                    mapAll["map"] = "magnus-internal/imagemap"
                    mapAll["mbd"] = "application/mbedlet"
                    mapAll["mct"] = "application/x-mascot"
                    mapAll["mdb"] = "application/x-msaccess"
                    mapAll["mdz"] = "audio/x-mod"
                    mapAll["me"] = "application/x-troff-me"
                    mapAll["mel"] = "text/x-vmel"
                    mapAll["mi"] = "application/x-mif"
                    mapAll["mid"] = "audio/midi"
                    mapAll["midi"] = "audio/midi"
                    mapAll["mif"] = "application/x-mif"
                    mapAll["mil"] = "image/x-cals"
                    mapAll["mio"] = "audio/x-mio"
                    mapAll["mmf"] = "application/x-skt-lbs"
                    mapAll["mng"] = "video/x-mng"
                    mapAll["mny"] = "application/x-msmoney"
                    mapAll["moc"] = "application/x-mocha"
                    mapAll["mocha"] = "application/x-mocha"
                    mapAll["mod"] = "audio/x-mod"
                    mapAll["mof"] = "application/x-yumekara"
                    mapAll["mol"] = "chemical/x-mdl-molfile"
                    mapAll["mop"] = "chemical/x-mopac-input"
                    mapAll["mov"] = "video/quicktime"
                    mapAll["movie"] = "video/x-sgi-movie"
                    mapAll["mp2"] = "audio/x-mpeg"
                    mapAll["mp3"] = "audio/x-mpeg"
                    mapAll["mp4"] = "video/mp4"
                    mapAll["mpc"] = "application/vnd.mpohun.certificate"
                    mapAll["mpe"] = "video/mpeg"
                    mapAll["mpeg"] = "video/mpeg"
                    mapAll["mpg"] = "video/mpeg"
                    mapAll["mpg4"] = "video/mp4"
                    mapAll["mpga"] = "audio/mpeg"
                    mapAll["mpn"] = "application/vnd.mophun.application"
                    mapAll["mpp"] = "application/vnd.ms-project"
                    mapAll["mps"] = "application/x-mapserver"
                    mapAll["mrl"] = "text/x-mrml"
                    mapAll["mrm"] = "application/x-mrm"
                    mapAll["ms"] = "application/x-troff-ms"
                    mapAll["mts"] = "application/metastream"
                    mapAll["mtx"] = "application/metastream"
                    mapAll["mtz"] = "application/metastream"
                    mapAll["mzv"] = "application/metastream"
                    mapAll["nar"] = "application/zip"
                    mapAll["nbmp"] = "image/nbmp"
                    mapAll["nc"] = "application/x-netcdf"
                    mapAll["ndb"] = "x-lml/x-ndb"
                    mapAll["ndwn"] = "application/ndwn"
                    mapAll["nif"] = "application/x-nif"
                    mapAll["nmz"] = "application/x-scream"
                    mapAll["nokia-op-logo"] = "image/vnd.nok-oplogo-color"
                    mapAll["npx"] = "application/x-netfpx"
                    mapAll["nsnd"] = "audio/nsnd"
                    mapAll["nva"] = "application/x-neva1"
                    mapAll["oda"] = "application/oda"
                    mapAll["oom"] = "application/x-AtlasMate-Plugin"
                    mapAll["pac"] = "audio/x-pac"
                    mapAll["pae"] = "audio/x-epac"
                    mapAll["pan"] = "application/x-pan"
                    mapAll["pbm"] = "image/x-portable-bitmap"
                    mapAll["pcx"] = "image/x-pcx"
                    mapAll["pda"] = "image/x-pda"
                    mapAll["pdb"] = "chemical/x-pdb"
                    mapAll["pdf"] = "application/pdf"
                    mapAll["pfr"] = "application/font-tdpfr"
                    mapAll["pgm"] = "image/x-portable-graymap"
                    mapAll["pict"] = "image/x-pict"
                    mapAll["pm"] = "application/x-perl"
                    mapAll["pmd"] = "application/x-pmd"
                    mapAll["png"] = "image/png"
                    mapAll["pnm"] = "image/x-portable-anymap"
                    mapAll["pnz"] = "image/png"
                    mapAll["pot"] = "application/vnd.ms-powerpoint"
                    mapAll["ppm"] = "image/x-portable-pixmap"
                    mapAll["pps"] = "application/vnd.ms-powerpoint"
                    mapAll["ppt"] = "application/vnd.ms-powerpoint"
                    mapAll["pqf"] = "application/x-cprplayer"
                    mapAll["pqi"] = "application/cprplayer"
                    mapAll["prc"] = "application/x-prc"
                    mapAll["proxy"] = "application/x-ns-proxy-autoconfig"
                    mapAll["ps"] = "application/postscript"
                    mapAll["ptlk"] = "application/listenup"
                    mapAll["pub"] = "application/x-mspublisher"
                    mapAll["pvx"] = "video/x-pv-pvx"
                    mapAll["qcp"] = "audio/vnd.qcelp"
                    mapAll["qt"] = "video/quicktime"
                    mapAll["qti"] = "image/x-quicktime"
                    mapAll["qtif"] = "image/x-quicktime"
                    mapAll["r3t"] = "text/vnd.rn-realtext3d"
                    mapAll["ra"] = "audio/x-pn-realaudio"
                    mapAll["ram"] = "audio/x-pn-realaudio"
                    mapAll["rar"] = "application/x-rar-compressed"
                    mapAll["ras"] = "image/x-cmu-raster"
                    mapAll["rdf"] = "application/rdf+xml"
                    mapAll["rf"] = "image/vnd.rn-realflash"
                    mapAll["rgb"] = "image/x-rgb"
                    mapAll["rlf"] = "application/x-richlink"
                    mapAll["rm"] = "audio/x-pn-realaudio"
                    mapAll["rmf"] = "audio/x-rmf"
                    mapAll["rmm"] = "audio/x-pn-realaudio"
                    mapAll["rmvb"] = "audio/x-pn-realaudio"
                    mapAll["rnx"] = "application/vnd.rn-realplayer"
                    mapAll["roff"] = "application/x-troff"
                    mapAll["rp"] = "image/vnd.rn-realpix"
                    mapAll["rpm"] = "audio/x-pn-realaudio-plugin"
                    mapAll["rt"] = "text/vnd.rn-realtext"
                    mapAll["rte"] = "x-lml/x-gps"
                    mapAll["rtf"] = "application/rtf"
                    mapAll["rtg"] = "application/metastream"
                    mapAll["rtx"] = "text/richtext"
                    mapAll["rv"] = "video/vnd.rn-realvideo"
                    mapAll["rwc"] = "application/x-rogerwilco"
                    mapAll["s3m"] = "audio/x-mod"
                    mapAll["s3z"] = "audio/x-mod"
                    mapAll["sca"] = "application/x-supercard"
                    mapAll["scd"] = "application/x-msschedule"
                    mapAll["sdf"] = "application/e-score"
                    mapAll["sea"] = "application/x-stuffit"
                    mapAll["sgm"] = "text/x-sgml"
                    mapAll["sgml"] = "text/x-sgml"
                    mapAll["sh"] = "application/x-sh"
                    mapAll["shar"] = "application/x-shar"
                    mapAll["shtml"] = "magnus-internal/parsed-html"
                    mapAll["shw"] = "application/presentations"
                    mapAll["si6"] = "image/si6"
                    mapAll["si7"] = "image/vnd.stiwap.sis"
                    mapAll["si9"] = "image/vnd.lgtwap.sis"
                    mapAll["sis"] = "application/vnd.symbian.install"
                    mapAll["sit"] = "application/x-stuffit"
                    mapAll["skd"] = "application/x-Koan"
                    mapAll["skm"] = "application/x-Koan"
                    mapAll["skp"] = "application/x-Koan"
                    mapAll["skt"] = "application/x-Koan"
                    mapAll["slc"] = "application/x-salsa"
                    mapAll["smd"] = "audio/x-smd"
                    mapAll["smi"] = "application/smil"
                    mapAll["smil"] = "application/smil"
                    mapAll["smp"] = "application/studiom"
                    mapAll["smz"] = "audio/x-smd"
                    mapAll["snd"] = "audio/basic"
                    mapAll["spc"] = "text/x-speech"
                    mapAll["spl"] = "application/futuresplash"
                    mapAll["spr"] = "application/x-sprite"
                    mapAll["sprite"] = "application/x-sprite"
                    mapAll["spt"] = "application/x-spt"
                    mapAll["src"] = "application/x-wais-source"
                    mapAll["stk"] = "application/hyperstudio"
                    mapAll["stm"] = "audio/x-mod"
                    mapAll["sv4cpio"] = "application/x-sv4cpio"
                    mapAll["sv4crc"] = "application/x-sv4crc"
                    mapAll["svf"] = "image/vnd"
                    mapAll["svg"] = "image/svg-xml"
                    mapAll["svh"] = "image/svh"
                    mapAll["svr"] = "x-world/x-svr"
                    mapAll["swf"] = "application/x-shockwave-flash"
                    mapAll["swfl"] = "application/x-shockwave-flash"
                    mapAll["t"] = "application/x-troff"
                    mapAll["tad"] = "application/octet-stream"
                    mapAll["talk"] = "text/x-speech"
                    mapAll["tar"] = "application/x-tar"
                    mapAll["taz"] = "application/x-tar"
                    mapAll["tbp"] = "application/x-timbuktu"
                    mapAll["tbt"] = "application/x-timbuktu"
                    mapAll["tcl"] = "application/x-tcl"
                    mapAll["tex"] = "application/x-tex"
                    mapAll["texi"] = "application/x-texinfo"
                    mapAll["texinfo"] = "application/x-texinfo"
                    mapAll["tgz"] = "application/x-tar"
                    mapAll["thm"] = "application/vnd.eri.thm"
                    mapAll["tif"] = "image/tiff"
                    mapAll["tiff"] = "image/tiff"
                    mapAll["tki"] = "application/x-tkined"
                    mapAll["tkined"] = "application/x-tkined"
                    mapAll["toc"] = "application/toc"
                    mapAll["toy"] = "image/toy"
                    mapAll["tr"] = "application/x-troff"
                    mapAll["trk"] = "x-lml/x-gps"
                    mapAll["trm"] = "application/x-msterminal"
                    mapAll["tsi"] = "audio/tsplayer"
                    mapAll["tsp"] = "application/dsptype"
                    mapAll["tsv"] = "text/tab-separated-values"
                    mapAll["ttf"] = "application/octet-stream"
                    mapAll["ttz"] = "application/t-time"
                    mapAll["txt"] = "text/plain"
                    mapAll["ult"] = "audio/x-mod"
                    mapAll["ustar"] = "application/x-ustar"
                    mapAll["uu"] = "application/x-uuencode"
                    mapAll["uue"] = "application/x-uuencode"
                    mapAll["vcd"] = "application/x-cdlink"
                    mapAll["vcf"] = "text/x-vcard"
                    mapAll["vdo"] = "video/vdo"
                    mapAll["vib"] = "audio/vib"
                    mapAll["viv"] = "video/vivo"
                    mapAll["vivo"] = "video/vivo"
                    mapAll["vmd"] = "application/vocaltec-media-desc"
                    mapAll["vmf"] = "application/vocaltec-media-file"
                    mapAll["vmi"] = "application/x-dreamcast-vms-info"
                    mapAll["vms"] = "application/x-dreamcast-vms"
                    mapAll["vox"] = "audio/voxware"
                    mapAll["vqe"] = "audio/x-twinvq-plugin"
                    mapAll["vqf"] = "audio/x-twinvq"
                    mapAll["vql"] = "audio/x-twinvq"
                    mapAll["vre"] = "x-world/x-vream"
                    mapAll["vrml"] = "x-world/x-vrml"
                    mapAll["vrt"] = "x-world/x-vrt"
                    mapAll["vrw"] = "x-world/x-vream"
                    mapAll["vts"] = "workbook/formulaone"
                    mapAll["wav"] = "audio/x-wav"
                    mapAll["wax"] = "audio/x-ms-wax"
                    mapAll["wbmp"] = "image/vnd.wap.wbmp"
                    mapAll["web"] = "application/vnd.xara"
                    mapAll["wi"] = "image/wavelet"
                    mapAll["wis"] = "application/x-InstallShield"
                    mapAll["wm"] = "video/x-ms-wm"
                    mapAll["wma"] = "audio/x-ms-wma"
                    mapAll["wmd"] = "application/x-ms-wmd"
                    mapAll["wmf"] = "application/x-msmetafile"
                    mapAll["wml"] = "text/vnd.wap.wml"
                    mapAll["wmlc"] = "application/vnd.wap.wmlc"
                    mapAll["wmls"] = "text/vnd.wap.wmlscript"
                    mapAll["wmlsc"] = "application/vnd.wap.wmlscriptc"
                    mapAll["wmlscript"] = "text/vnd.wap.wmlscript"
                    mapAll["wmv"] = "audio/x-ms-wmv"
                    mapAll["wmx"] = "video/x-ms-wmx"
                    mapAll["wmz"] = "application/x-ms-wmz"
                    mapAll["wpng"] = "image/x-up-wpng"
                    mapAll["wpt"] = "x-lml/x-gps"
                    mapAll["wri"] = "application/x-mswrite"
                    mapAll["wrl"] = "x-world/x-vrml"
                    mapAll["wrz"] = "x-world/x-vrml"
                    mapAll["ws"] = "text/vnd.wap.wmlscript"
                    mapAll["wsc"] = "application/vnd.wap.wmlscriptc"
                    mapAll["wv"] = "video/wavelet"
                    mapAll["wvx"] = "video/x-ms-wvx"
                    mapAll["wxl"] = "application/x-wxl"
                    mapAll["x-gzip"] = "application/x-gzip"
                    mapAll["xar"] = "application/vnd.xara"
                    mapAll["xbm"] = "image/x-xbitmap"
                    mapAll["xdm"] = "application/x-xdma"
                    mapAll["xdma"] = "application/x-xdma"
                    mapAll["xdw"] = "application/vnd.fujixerox.docuworks"
                    mapAll["xht"] = "application/xhtml+xml"
                    mapAll["xhtm"] = "application/xhtml+xml"
                    mapAll["xhtml"] = "application/xhtml+xml"
                    mapAll["xla"] = "application/vnd.ms-excel"
                    mapAll["xlc"] = "application/vnd.ms-excel"
                    mapAll["xll"] = "application/x-excel"
                    mapAll["xlm"] = "application/vnd.ms-excel"
                    mapAll["xls"] = "application/vnd.ms-excel"
                    mapAll["xlt"] = "application/vnd.ms-excel"
                    mapAll["xlw"] = "application/vnd.ms-excel"
                    mapAll["xm"] = "audio/x-mod"
                    mapAll["xml"] = "text/xml"
                    mapAll["xmz"] = "audio/x-mod"
                    mapAll["xpi"] = "application/x-xpinstall"
                    mapAll["xpm"] = "image/x-xpixmap"
                    mapAll["xsit"] = "text/xml"
                    mapAll["xsl"] = "text/xml"
                    mapAll["xul"] = "text/xul"
                    mapAll["xwd"] = "image/x-xwindowdump"
                    mapAll["xyz"] = "chemical/x-pdb"
                    mapAll["yz1"] = "application/x-yz1"
                    mapAll["z"] = "application/x-compress"
                    mapAll["zac"] = "application/x-zaurus-zac"
                    mapAll["zip"] = "application/zip"
                }
                return mapAll
            }
    }
}